### ISSUE TITLE
SyntaxError: Unexpected token '?'  

### ISSUE THREAD

**Issue by extgfx** [SidisLiveYT/Video-Extractor#3]
### Tried to download with either URL and Keyword, returned the same error result.
>Code:
```
const { Extractor } = require('video-extractor')

const all = process.argv
const args = all.slice(2);
console.log(args);
console.log(args[0])

if (args[0] == 'dl' && args.length > 1) {
	const url = args[1]
	const Data = Extractor(url)
	console.log(Data)
}
```
>Error Log:
```
C:\Users\Fumiko\Documents\nodeTest\node_modules\video-extractor\src\bin\Spotify-Resolver.js:37
?? VideoThumbnailPreview.link 
^ 
SyntaxError: Unexpected token '?' 
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1053:16)←[39m 
←[90m    at Module._compile (internal/modules/cjs/loader.js:1101:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:985:32)←[39m 
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
at Object.<anonymous> (C:\Users\Fumiko\Documents\nodeTest\node_modules\←[4mvideo-extractor←[24m\src\index.js:1:26)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m 
```

**Comment by SidisLiveYT** [comment]
may be a TypeError from my side , I am checking
